name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
        with:
          install: true
          cache: true
      - run: uv sync --all-extras
      - run: ruff format --check . && ruff check .
      - run: uvx ty check .
      - run: uv run pytest
